### ISSUE TITLE
Where are the front end files 

### ISSUE THREAD

**Issue by rizerzero** [sustained/ascension#1]
Hi, Thank you for sharing this code, I wanted to test and see how it was working cause I wanted to build an SRS app, but I could not find the frontend files for this project, it seems like this code is just a backend API.

Thank you 😁

**Comment by sustained** [comment]
If there were are frontend files they'd be in the `resources/js` directory.

Unfortunately there aren't any because I didn't really do much with this project. I've been without a computer and internet for 6-8 weeks. But that just changed and I plan to get back into the swing of things and start working on projects again soon.

So maybe keep an eye on the repository.

**Comment by sustained** [comment]
There's some stuff [here](https://github.com/sustained/srs-components/tree/master/src/components) that may or may not be of use to you but there's really not much and I doubt it's any good, it was just basically me learning Vue and taking a very first attempt at some basic SRS stuff. I don't think that repo will be updated, nor will it be supported. But this one may well be!
